### ISSUE TITLE
TGUgZmlndXJlIFggZSBPIHNvbm8gZGlzYWxsaW5lYXRl

### ISSUE THREAD

**Issue by Cyanogene** [Giackmar/Tris#1]
U3VsIG1pbyB0ZWxlZm9ubyBYaWFvbWkgUmVkbWkgbm90ZSA1IHBybywgbGUgaWNvbmUgbm9uIHNvbm8gdG90YWxtZW50ZSBhbGxpbmVhdGUu

**Comment by Giackmar** [comment]
U2VpIHVuIG5hYmJvaWRl
